name: Flow 

on: [pull_request]

jobs:
  flow:
    name: Type checking with Flow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Copy package.json to root
      run: cp install/package.json package.json

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Flow
      run: npm install --save-dev flow-bin

    - name: Run Flow
      run: npx flow

    # Optional step to clean up
    - name: Remove package.json from root
      run: rm package.json